[package]
name = "wascap"
version = "0.4.4"
authors = ["Kevin Hoffman <alothien@gmail.com>"]
edition = "2018"
description = "Extracting, embedding, and validating WebAssembly Standard Capabilities tokens"
license = "Apache-2.0"
homepage = "https://github.com/wascc"
documentation = "https://docs.rs/wascap"
readme = "README.md"
keywords = ["jwt", "crypto", "ed25519", "security", "webassembly"]
categories = ["cryptography", "authentication", "wasm"]

[badges]
travis-ci = { repository = "wascc/wascap", branch = "master" }

[features]
cli = ["quicli", "structopt", "term-table", "exitfailure"]

[[bin]]
name = "wascap"
required-features = ["cli"]

[dependencies]
log = "0.4.8"
env_logger = "0.7.1"
serde_derive = "1"
serde = "1"
nkeys = "0.0.9"
base64 = "0.11.0"
serde_json = "1.0.48"
nuid = "0.2.1"
parity-wasm = "0.41.0"
lazy_static = "1.4.0"
ring = "0.16.11"
data-encoding = "2.1.2"
chrono-humanize = "0.0.11"
chrono = "0.4.10"

quicli = { version = "0.4", optional = true }
structopt = { version = "0.3.9", optional = true }
term-table = { version = "1.2.0", optional = true }
exitfailure = { version = "0.5.1", optional =true }
